baseURL = "https://diary.moreimpress.com/"
languageCode = "en-us"
title = "mi-Diary"
theme = "mi-diary"
summaryLength = "15"

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = ""
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = ""
    url = "/tags/"
    weight = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"    