baseURL = "/"
languageCode = "en-us"
title = "mi-Diary"
theme = "mi-bootstrap-5"
summaryLength = "15"

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = ""
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = ""
    url = "/tags/"
    weight = 3